# Generated by Django 3.1.7 on 2021-03-29 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_messages', '0002_auto_20210327_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
    ]
